[package]
name = "walnut"
version = "0.1.0"
authors = ["Chrislearn Young <chris@acroidea.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
multimap = "0.3"
url = "2.1"
lazy_static = "1.4"